version: '3.8'

services:
  database:
    image: mysql:8.4
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password_here
      MYSQL_DATABASE: databasename_here
    ports:
      - "3306:3306"
    # Memory for database (init from folder:sql-scripts !!!)
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  backend:
    image: user_here/projectname_here:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      # Application
      SPRING_APPLICATION_NAME: backend

      # Datasource
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/databasename_here?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password_here
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      # CORS
      MOESIF_CORS_ALLOW_ORIGINS: "http://127.0.0.1:5500,http://localhost:4200"
      MOESIF_CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      MOESIF_CORS_ALLOW_HEADERS: "Authorization,Content-Type"
      MOESIF_CORS_ALLOW_CREDENTIALS: "true"

      # App-specific
      APP_BASE_URL: http://localhost:8080

  frontend:
    image: user_here/projectname_here:latest
    container_name: frontend
    ports:
      - "80:80"