services:
  database:
    image: mysql:8.4
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DATABASENAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    # Memory for database (init from folder:sql-scripts !!!)
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  backend:
    image: ${BACKEND_DEV_DOCKERHUB}/${BACKEND_PROJECT_DOCKERHUB}:latest
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - database
    environment:
      # Application
      SPRING_APPLICATION_NAME: backend

      # Datasource
      SPRING_DATASOURCE_URL: jdbc:mysql://database:${DATABASE_PORT}/${DATABASENAME}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      # CORS
      MOESIF_CORS_ALLOW_ORIGINS: "${ALLOW_CORS_ORIGIN}"
      MOESIF_CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      MOESIF_CORS_ALLOW_HEADERS: "Authorization,Content-Type"
      MOESIF_CORS_ALLOW_CREDENTIALS: "true"

      # App-specific
      APP_BASE_URL: ${APP_BASE_URL}

  frontend:
    image: ${FRONTEND_DEV_DOCKERHUB}/${FRONTEND_PROJECT_DOCKERHUB}:latest
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      BACKEND_BASE_URL: ${APP_BASE_URL}
    depends_on:
      - backend